# Generated by Django 5.2.11 on 2026-03-11 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('clients', '0010_alter_client_active_status'),
        ('services', '0009_alter_workorder_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Servicio sin IVA')),
                ('iva_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='15% IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('factura', models.CharField(blank=True, max_length=200, null=True, verbose_name='Factura')),
                ('credito', models.CharField(blank=True, max_length=200, null=True, verbose_name='Crédito')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='clients.client', verbose_name='Cliente')),
                ('service_catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecatalog', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Registro de Facturación',
                'verbose_name_plural': 'Registros de Facturación',
                'ordering': ['-anio', '-mes', 'client__name'],
            },
        ),
    ]
