# Generated by Django 5.2.11 on 2026-03-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='service_label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre Servicio'),
        ),
    ]
