# Generated by Django 5.2.11 on 2026-02-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="totp_secret",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Secreto TOTP"
            ),
        ),
    ]
