# Generated by Django 5.2.11 on 2026-02-23 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Servicio"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("HOUSING", "Housing/Colocation"),
                            ("TELECOM", "Telecom / Internet"),
                            ("APP_DEV", "Desarrollo de Software"),
                            ("OTHER", "Otros Servicios"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Precio Base",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP Asignada"
                    ),
                ),
                (
                    "rack_space",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Espacio en Rack",
                    ),
                ),
                (
                    "bandwidth",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ancho de Banda",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("SUSPENDED", "Suspendido"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "agreed_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio Acordado"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Fin"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="clients.client",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="services.servicecatalog",
                    ),
                ),
            ],
        ),
    ]
