# Generated by Django 5.2.11 on 2026-02-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='status',
            field=models.CharField(choices=[('PROSPECTING', 'Prospección'), ('CONTACTED', 'Contactado'), ('FIRST_MEETING', 'Primera Cita'), ('OFFERED', 'Ofertado'), ('FOLLOW_UP', 'Seguimiento'), ('CLOSING_MEETING', 'Cita de Cierre'), ('DEMO', 'Demo'), ('CONTRACT_SIGNED', 'Firma de Contrato'), ('BACKLOG', 'Backlog'), ('INSTALLED', 'Instalado'), ('LOST', 'Negocio Perdido')], default='PROSPECTING', max_length=20),
        ),
    ]
