# Generated by Django 5.2.11 on 2026-02-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_clientservice_call_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecatalog",
            name="base_cost",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Costo Base"
            ),
        ),
    ]
