# Generated by Django 5.2.11 on 2026-02-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_clientservice_status'),
        ('services', '0002_clientservice_call_result_and_more'),
    ]

    operations = [
    ]
