# Generated by Django 5.2.11 on 2026-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_servicecatalog_base_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecatalog",
            name="client_taxes",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Impuestos del Cliente",
            ),
        ),
        migrations.AddField(
            model_name="servicecatalog",
            name="internal_code",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Código Referencia Interna",
            ),
        ),
        migrations.AlterField(
            model_name="servicecatalog",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Servicio"),
        ),
        migrations.AlterField(
            model_name="servicecatalog",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOUSING", "Housing/Colocation"),
                    ("TELECOM", "Telecom / Internet"),
                    ("APP_DEV", "Desarrollo de Software"),
                    ("OTHER", "Otros Servicios"),
                ],
                default="OTHER",
                max_length=20,
                null=True,
            ),
        ),
    ]
