# Generated by Django 5.2.11 on 2026-02-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_merge_20260225_1434'),
        ('services', '0003_servicecatalog_base_cost'),
    ]

    operations = [
    ]
