# Generated by Django 5.2.11 on 2026-03-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_merge_20260225_1927'),
        ('services', '0004_servicecatalog_client_taxes_and_more'),
    ]

    operations = [
    ]
