# Generated by Django 5.2.11 on 2026-03-10 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_servicecatalog_client_taxes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicecatalog",
            options={
                "ordering": ["name"],
                "verbose_name": "Catálogo de Servicio",
                "verbose_name_plural": "Catálogo de Servicios",
            },
        ),
        migrations.AddField(
            model_name="clientservice",
            name="service_location",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Ubicación del Servicio",
            ),
        ),
        migrations.AlterField(
            model_name="clientservice",
            name="bandwidth",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Velocidad (Mbps)"
            ),
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=100, verbose_name="Orden de Instalación #"
                    ),
                ),
                ("login", models.CharField(max_length=255, verbose_name="Login")),
                (
                    "estimated_date",
                    models.DateTimeField(
                        verbose_name="Fecha y Hora Estimada Instalación"
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_order",
                        to="services.clientservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Trabajo",
                "verbose_name_plural": "Órdenes de Trabajo",
            },
        ),
    ]
