# Generated by Django 5.2.11 on 2026-03-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_merge_20260305_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='service_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación del Servicio'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Velocidad (Mbps)'),
        ),
    ]
