# Generated by Django 5.2.11 on 2026-03-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_clientservice_service_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecatalog',
            options={'ordering': ['name'], 'verbose_name': 'Catálogo de Servicio', 'verbose_name_plural': 'Catálogo de Servicios'},
        ),
    ]
