# Generated by Django 5.2.11 on 2026-03-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_workorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='order_number',
            field=models.CharField(max_length=100, verbose_name='Orden de Instalación #'),
        ),
    ]
