# Generated by Django 5.2.11 on 2026-02-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="account_manager",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Gerente de Cuenta"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ciudad"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Región"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="segment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Segmento"
            ),
        ),
    ]
