# Generated by Django 5.2.11 on 2026-03-02 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_account_manager_client_city_client_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="classification",
            field=models.CharField(
                choices=[("PROSPECT", "Prospecto"), ("ACTIVE", "Cliente Activo")],
                default="PROSPECT",
                max_length=20,
                verbose_name="Clasificación",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="prospect_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIRST_MEETING", "Primera Cita"),
                    ("CONTACTED", "Contactado"),
                    ("OFFERED", "Ofertado"),
                    ("FOLLOW_UP", "Seguimiento"),
                    ("CLOSING_MEETING", "Cita Cierre"),
                    ("ADJUDICATED", "Adjudicado"),
                    ("TDR_ELABORATION", "Elaboración de TDR"),
                    ("LOST_DEAL", "Negocio Perdido"),
                ],
                max_length=30,
                null=True,
                verbose_name="Estado de Prospecto",
            ),
        ),
        migrations.CreateModel(
            name="ClientStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FIRST_MEETING", "Primera Cita"),
                            ("CONTACTED", "Contactado"),
                            ("OFFERED", "Ofertado"),
                            ("FOLLOW_UP", "Seguimiento"),
                            ("CLOSING_MEETING", "Cita Cierre"),
                            ("ADJUDICATED", "Adjudicado"),
                            ("TDR_ELABORATION", "Elaboración de TDR"),
                            ("LOST_DEAL", "Negocio Perdido"),
                        ],
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Razón")),
                (
                    "evidence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="prospect_evidence/",
                        verbose_name="Evidencia",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="clients.client",
                    ),
                ),
            ],
        ),
    ]
