# Generated by Django 5.2.11 on 2026-03-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_client_classification_client_prospect_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientstatushistory",
            name="mrc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="MRC",
            ),
        ),
        migrations.AddField(
            model_name="clientstatushistory",
            name="nrc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="NRC",
            ),
        ),
    ]
