# Generated by Django 5.2.11 on 2026-03-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_clientstatushistory_mrc_clientstatushistory_nrc"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientstatushistory",
            name="custom_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha Reportada"
            ),
        ),
        migrations.AlterField(
            model_name="clientstatushistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Fecha Sistema"),
        ),
    ]
