# Generated by Django 5.2.11 on 2026-03-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_clientstatushistory_custom_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="active_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BACKLOG", "Backlog"),
                    ("BILLED", "Facturado"),
                    ("NEW_SERVICE", "Servicio Nuevo"),
                    ("DOWN_GRADE", "Down Grade"),
                    ("UP_GRADE", "Up Grade"),
                    ("DEMO", "Demo"),
                ],
                max_length=30,
                null=True,
                verbose_name="Estado de Activo",
            ),
        ),
        migrations.AlterField(
            model_name="clientstatushistory",
            name="status",
            field=models.CharField(max_length=100, verbose_name="Estado"),
        ),
    ]
