# Generated by Django 5.2.11 on 2026-03-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_active_status_and_more'),
        ('services', '0005_merge_20260305_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_type',
        ),
        migrations.AddField(
            model_name='client',
            name='client_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecatalog', verbose_name='Tipo de Cliente'),
        ),
    ]
