# Generated by Django 5.2.11 on 2026-03-05 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_client_active_status_and_more"),
        ("services", "0004_servicecatalog_client_taxes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="client_type",
        ),
        migrations.AddField(
            model_name="client",
            name="client_type_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.servicecatalog",
                verbose_name="Tipo de Cliente",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="service_location",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Ubicación del Servicio",
            ),
        ),
    ]
