# Generated by Django 5.2.11 on 2026-03-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_remove_client_client_type_client_client_type_new_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="active_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PROSPECTING", "Prospección"),
                    ("CONTACTED", "Contactado"),
                    ("FIRST_MEETING", "Primera Cita"),
                    ("OFFERED", "Ofertado"),
                    ("FOLLOW_UP", "Seguimiento"),
                    ("CLOSING_MEETING", "Cita de Cierre"),
                    ("DEMO", "Demo"),
                    ("CONTRACT_SIGNED", "Firma de Contrato"),
                    ("BACKLOG", "Backlog"),
                    ("INSTALLED", "Instalado"),
                    ("BILLED", "Facturado"),
                    ("NEW_SERVICE", "Servicio Nuevo"),
                    ("DOWN_GRADE", "Down Grade"),
                    ("UP_GRADE", "Up Grade"),
                    ("LOST", "Negocio Perdido"),
                ],
                max_length=30,
                null=True,
                verbose_name="Estado de Activo",
            ),
        ),
    ]
