# Generated by Django 5.2.11 on 2026-03-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_client_client_type_client_client_type_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='service_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación del Servicio'),
        ),
    ]
