# Generated by Django 5.2.11 on 2026-03-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_client_client_type_client_client_type_new_and_more'),
        ('clients', '0008_client_service_location'),
    ]

    operations = [
    ]
