# Generated by Django 5.2.11 on 2026-03-30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_alter_client_active_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="account_manager",
            new_name="account_manager_legacy",
        ),
        migrations.AddField(
            model_name="client",
            name="account_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="managed_clients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gerente de Cuenta",
            ),
        ),
    ]
