# Generated by Django 5.2.11 on 2026-03-30

from django.conf import settings
from django.db import migrations
from django.db.models import CharField, F, Value
from django.db.models.functions import Concat


def migrate_account_manager_to_fk(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    db_alias = schema_editor.connection.alias

    clients = Client.objects.using(db_alias).exclude(account_manager_legacy__isnull=True)

    for client in clients.iterator():
        legacy_name = " ".join((client.account_manager_legacy or "").split())
        if not legacy_name:
            continue

        try:
            matches = list(
                User.objects.using(db_alias)
                .annotate(
                    full_name=Concat(
                        F("first_name"),
                        Value(" "),
                        F("last_name"),
                        output_field=CharField(),
                    )
                )
                .filter(full_name__icontains=legacy_name)[:2]
            )

            if len(matches) == 1:
                client.account_manager_id = matches[0].id
                client.save(update_fields=["account_manager"])
        except Exception:
            # Data migration must never fail because of malformed names or users.
            continue


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("clients", "0009_client_account_manager_fk"),
    ]

    operations = [
        migrations.RunPython(migrate_account_manager_to_fk, noop_reverse),
        migrations.RemoveField(
            model_name="client",
            name="account_manager_legacy",
        ),
    ]
