# Generated by Django 5.2.11 on 2026-04-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_migrate_account_manager_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado del Negocio'),
        ),
        migrations.AddField(
            model_name='client',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='client',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
